# Map of plan files to SCM paths they consume
scm_deps = {'amiconfig.bob': set([('scc/amiconfig', ''),
                       ('scc/amiconfig-vmwareguest', '')]),
 'capsule-indexer.bob': set([('scc/rpath-capsule-indexer', '')]),
 'catalog-service.bob': set([('scc/catalog-service', '')]),
 'conary-policy.bob': set([('scc/conary-policy', '')]),
 'conary.bob': set([('scc/conary', '')]),
 'crest.bob': set([('scc/crest', '')]),
 'entsrv.bob': set([('scc/entsrv', '')]),
 'flex3p.bob': set([('scc/flex3p', '')]),
 'flexlibs.bob': set([('scc/flexlibs', '')]),
 'group-devimage-appliance.bob': set([('scc/recipes',
                                       'centos-6n/devimage-custom'),
                                      ('scc/recipes',
                                       'centos-6n/group-devimage-appliance')]),
 'group-entsrv.bob': set([('scc/recipes', 'centos-6n/group-entsrv-appliance')]),
 'group-rbuilder.bob': set([('scc/recipes', 'centos-6n/group-rbuilder-dist')]),
 'group-rpath-packages.bob': set([('scc/recipes',
                                   'centos-6n/group-rpath-packages')]),
 'group-rpath-platform.bob': set([('scc/recipes',
                                   'centos-6n/group-rpath-platform')]),
 'group-rwbs-appliance.bob': set([('scc/recipes',
                                   'centos-6n/group-rwbs-appliance')]),
 'group-updateservice.bob': set([('scc/recipes',
                                  'centos-6n/group-updateservice-appliance')]),
 'job.bob': set([('scc/rpath-job', '')]),
 'jobmaster.bob': set([('scc/jobmaster', '')]),
 'jobslave.bob': set([('scc/jobslave', '')]),
 'mcp.bob': set([('scc/mcp', '')]),
 'mint-test.bob': set([('scc/mint', '')]),
 'mint.bob': set([('scc/mint', '')]),
 'models.bob': set([('scc/rpath-models', '')]),
 'pcreator.bob': set([('scc/pcreator', '')]),
 'proddef.bob': set([('scc/rpath-product-definition', '')]),
 'product-definition-devimage-infra.bob': set([('scc/recipes',
                                                'product-definitions/devimage/product-definition')]),
 'product-definition-devimage.bob': set([('scc/recipes',
                                          'product-definitions/devimage/product-definition')]),
 'product-definition-entsrv.bob': set([('scc/recipes',
                                        'product-definitions/entsrv/product-definition')]),
 'product-definition-rba-infra.bob': set([('scc/recipes',
                                           'product-definitions/rba/product-definition')]),
 'product-definition-rba-vapp.bob': set([('scc/recipes',
                                          'product-definitions/rba/product-definition')]),
 'product-definition-rba.bob': set([('scc/recipes',
                                     'product-definitions/rba/product-definition')]),
 'product-definition-rus-infra.bob': set([('scc/recipes',
                                           'product-definitions/rus/product-definition')]),
 'product-definition-rus.bob': set([('scc/recipes',
                                     'product-definitions/rus/product-definition')]),
 'product-definition-rwbs-infra.bob': set([('scc/recipes',
                                            'product-definitions/rwbs/product-definition')]),
 'product-definition-rwbs.bob': set([('scc/recipes',
                                      'product-definitions/rwbs/product-definition')]),
 'pyovf.bob': set([('scc/pyovf', '')]),
 'rbuild.bob': set([('scc/rbuild', '')]),
 'rbuilder-ui.bob': set([('scc/rbuilder-ui', '')]),
 'repodata.bob': set([('scc/repodata', '')]),
 'restlib.bob': set([('scc/restlib', '')]),
 'rmake.bob': set([('scc/rmake', '')]),
 'rmake3.bob': set([('scc/rmake3', '')]),
 'robj.bob': set([('scc/robj', '')]),
 'rpath-repeater.bob': set([('scc/rpath-repeater', '')]),
 'rpath-tools.bob': set([('scc/rpath-tools', '')]),
 'smartform.bob': set([('scc/smartform', '')]),
 'storage.bob': set([('scc/rpath-storage', '')]),
 'upsrv.bob': set([('scc/rbm', '')]),
 'wmiclient.bob': set([('scc/wmiclient', '')]),
 'xml_resources.bob': set([('scc/xml_resources', '')]),
 'xmllib.bob': set([('scc/rpath-xmllib', '')]),
 'xobj.bob': set([('scc/xobj', '')])}
# map of providers to the set of requirers
dep_graph = {'amiconfig.bob': set(['group-rpath-packages.bob', 'jobslave.bob']),
 'capsule-indexer.bob': set(['mint.bob']),
 'catalog-service.bob': set(['mint.bob']),
 'conary-policy.bob': set(['conary.bob']),
 'conary.bob': set(['amiconfig.bob',
                    'flex3p.bob',
                    'group-rwbs-appliance.bob',
                    'models.bob',
                    'product-definition-devimage-infra.bob',
                    'product-definition-devimage.bob',
                    'product-definition-entsrv.bob',
                    'product-definition-rba-infra.bob',
                    'product-definition-rba-vapp.bob',
                    'product-definition-rba.bob',
                    'product-definition-rus-infra.bob',
                    'product-definition-rus.bob',
                    'product-definition-rwbs-infra.bob',
                    'product-definition-rwbs.bob',
                    'restlib.bob',
                    'rmake.bob',
                    'rmake3.bob',
                    'wmiclient.bob',
                    'xml_resources.bob',
                    'xmllib.bob',
                    'xobj.bob']),
 'crest.bob': set(['mint.bob']),
 'entsrv.bob': set(['group-entsrv.bob', 'group-rbuilder.bob']),
 'flex3p.bob': set(['flexlibs.bob']),
 'flexlibs.bob': set(['rbuilder-ui.bob']),
 'group-devimage-appliance.bob': set(),
 'group-entsrv.bob': set(),
 'group-rbuilder.bob': set(),
 'group-rpath-packages.bob': set(),
 'group-rpath-platform.bob': set(),
 'group-rwbs-appliance.bob': set(),
 'group-updateservice.bob': set(),
 'job.bob': set(['catalog-service.bob']),
 'jobmaster.bob': set(['group-rbuilder.bob']),
 'jobslave.bob': set(['catalog-service.bob']),
 'mcp.bob': set(['jobmaster.bob', 'mint.bob']),
 'mint-test.bob': set(),
 'mint.bob': set(['entsrv.bob', 'group-updateservice.bob', 'mint-test.bob']),
 'models.bob': set(['catalog-service.bob', 'rpath-tools.bob']),
 'pcreator.bob': set(['mint.bob']),
 'proddef.bob': set(['pcreator.bob', 'rbuild.bob']),
 'product-definition-devimage-infra.bob': set(),
 'product-definition-devimage.bob': set(),
 'product-definition-entsrv.bob': set(),
 'product-definition-rba-infra.bob': set(),
 'product-definition-rba-vapp.bob': set(),
 'product-definition-rba.bob': set(),
 'product-definition-rus-infra.bob': set(),
 'product-definition-rus.bob': set(),
 'product-definition-rwbs-infra.bob': set(),
 'product-definition-rwbs.bob': set(),
 'pyovf.bob': set(['jobslave.bob']),
 'rbuild.bob': set(['group-devimage-appliance.bob']),
 'rbuilder-ui.bob': set(['group-rbuilder.bob']),
 'repodata.bob': set(['capsule-indexer.bob']),
 'restlib.bob': set(['crest.bob', 'jobmaster.bob', 'jobslave.bob']),
 'rmake.bob': set(['catalog-service.bob',
                   'mcp.bob',
                   'pcreator.bob',
                   'rbuild.bob']),
 'rmake3.bob': set(['rpath-repeater.bob', 'upsrv.bob']),
 'robj.bob': set(['mint.bob', 'rbuild.bob']),
 'rpath-repeater.bob': set(['catalog-service.bob']),
 'rpath-tools.bob': set(['group-devimage-appliance.bob',
                         'group-entsrv.bob',
                         'group-rbuilder.bob',
                         'group-rpath-packages.bob',
                         'group-updateservice.bob']),
 'smartform.bob': set(['flexlibs.bob',
                       'pcreator.bob',
                       'rbuild.bob',
                       'rpath-repeater.bob',
                       'rpath-tools.bob']),
 'storage.bob': set(['job.bob']),
 'upsrv.bob': set(['group-updateservice.bob']),
 'wmiclient.bob': set(['rpath-repeater.bob']),
 'xml_resources.bob': set(['flexlibs.bob', 'rpath-tools.bob']),
 'xmllib.bob': set(['proddef.bob', 'repodata.bob', 'storage.bob']),
 'xobj.bob': set(['crest.bob', 'pyovf.bob', 'robj.bob', 'smartform.bob'])}
